apiVersion: v1
kind: Service
metadata:
  name: hungry-horse
  namespace: app-bar-prd
  labels:
    app: hungry-horse
    env: prd
spec:
  type: NodePort
  selector:
    app: hungry-horse
    env: prd
  ports:
      - nodePort: 31002
        protocol: TCP
        port: 8080
